CREATE TABLE LINE_ITEMS(ID STRING, NAME VARCHAR, PRICE DECIMAL(10, 2)
  WITH (KAFKA_TOPIC = 'retaildb_line_items',
        VALUE_FORMAT='JSON',
        KEY = 'ID');

CREATE TABLE USERS(ID INT, FIRST_NAME VARCHAR, LAST_NAME VARCHAR) WITH (KAFKA_TOPIC = 'retaildb_users',
  VALUE_FORMAT='JSON',
  KEY='ID');

CREATE STREAM BASKET_EVENT(ID VARCHAR, USER_ID INT, ITEM_ID INT, ITEM_NAME VARCHAR, ITEM_PRICE DECIMAL(10, 2), AMOUNT INT)
WITH (KAFKA_TOPIC = 'basket_event',
             VALUE_FORMAT='JSON',
             KEY = 'ID');

CREATE TABLE USER_BASKET
AS SELECT USER_ID, ITEM_ID, ITEM_NAME, ITEM_PRICE, SUM(AMOUNT)
FROM BASKET_EVENT
GROUP BY USER_ID, ITEM_ID, ITEM_NAME, ITEM_PRICE;

/*

*/

CREATE STREAM ORDER_EVENT(ID VARCHAR, USER_ID INT, ORDER STRUCT)
WITH (KAFKA_TOPIC = 'order_event',
             VALUE_FORMAT='JSON',
             KEY = 'ID');

CREATE TABLE ORDER_REPORT
AS SELECT COUNT(*) FROM ORDER_EVENT;

